### ISSUE TITLE
我根据你的docker步骤跑起来的，但是没有成功监听 50001 端口，但8000端口有正常监听。

### ISSUE THREAD

**Issue by sfter** [Next-DAO/atomicals-electrumx-docker#1]
我根据你的docker步骤跑起来的，但是没有成功监听 50001 端口，但8000端口有正常监听，这一般是什么原因，我看日志同步数据是正常的。

`INFO:electrumx:ElectrumX server starting
INFO:electrumx:logging level: INFO
INFO:Controller:Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
INFO:Controller:software version: ElectrumX 1.16.0
INFO:Controller:aiorpcX version: 0.22.1
INFO:Controller:supported protocol versions: 1.4-1.4.3
INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at 0x7fa4f436ace0>
INFO:Controller:reorg limit is 200 blocks
INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
INFO:DB:switching current directory to /root/.electrumx/db
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:UTXO DB version: 8
INFO:DB:coin: Bitcoin
INFO:DB:network: mainnet
INFO:DB:height: 164,850
INFO:DB:tip: 0000000000000c7c72a58daa1ef53e395e8644daf6798d227f48fcf888a56e99
INFO:DB:tx count: 2,322,665
INFO:DB:atomical count: 0
INFO:DB:flushing DB cache at 400 MB
INFO:DB:sync time so far: 06m 01s
INFO:History:history DB version: 1
INFO:History:flush count: 6
INFO:SessionManager:RPC server listening on 0.0.0.0:8000
INFO:Prefetcher:catching up to daemon height 816,419 (651,569 blocks behind)
INFO:BlockProcessor:our height: 164,860 daemon: 816,419 UTXOs 0MB hist 0MB
INFO:BlockProcessor:our height: 170,860 daemon: 816,419 UTXOs 51MB hist 73MB

INFO:BlockProcessor:our height: 177,260 daemon: 816,419 UTXOs 87MB hist 149MB
INFO:DB:flushed filesystem data in 1.64s
INFO:History:flushed history in 5.2s for 659,312 addrs
INFO:DB:flush #7 took 7.1s.  Height 177,260 txs: 2,919,400 (+596,735) Atomical txs: 0 (+0)
INFO:DB:tx/sec since genesis: 6,505, since last flush: 6,862
INFO:DB:sync time: 07m 28s  ETA: 2d 18h 24m
INFO:BlockProcessor:our height: 180,060 daemon: 816,419 UTXOs 101MB hist 54MB
INFO:BlockProcessor:our height: 181,545 daemon: 816,419 UTXOs 111MB hist 107MB
INFO:DB:flushed filesystem data in 0.02s
INFO:History:flushed history in 1.5s for 442,297 addrs
INFO:DB:flush #8 took 1.5s.  Height 181,545 txs: 3,453,157 (+533,757) Atomical txs: 0 (+0)
INFO:DB:tx/sec since genesis: 6,727, since last flush: 8,272
INFO:DB:sync time: 08m 33s  ETA: 2d 06h 51m

INFO:BlockProcessor:our height: 183,167 daemon: 816,419 UTXOs 121MB hist 61MB
INFO:LocalRPC:[0] RPC 212.70.149.142:57789, 0 total
INFO:BlockProcessor:our height: 184,414 daemon: 816,419 UTXOs 130MB hist 104MB
INFO:DB:flushed filesystem data in 0.09s
INFO:History:flushed history in 1.5s for 414,242 addrs
INFO:DB:flush #9 took 1.6s.  Height 184,414 txs: 4,036,035 (+582,878) Atomical txs: 0 (+0)
INFO:DB:tx/sec since genesis: 6,944, since last flush: 8,584
INFO:DB:sync time: 09m 41s  ETA: 2d 04h 43m
INFO:BlockProcessor:our height: 184,856 daemon: 816,419 UTXOs 132MB hist 28MB`

**Comment by lucky2077** [comment]
看这个log `our height: 184,856 daemon: 816,419`，在索引完成之前，不会实际监听相关端口

**Comment by lucky2077** [comment]
我也是在写 electrum-proxy Dockerfile 的时候发现这个事情的，因此通过这个端口来判断 electrumx 是否 healthy https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/blob/bf78ac55cfd90c41a2291752e3a5b80fe6591a20/docker-compose.yml#L17

**Comment by GeekXtop** [comment]
同样的问题，已经追上当前区块但是依然没有启动50001端口

**Comment by kukuxz007** [comment]
{"success":false,"health":false,"message":"Cannot read properties of null (reading 'serverDonation_address')"} 报这个错

**Comment by hhfcvmars** [comment]
> {"success":false,"health":false,"message":"Cannot read properties of null (reading 'serverDonation_address')"} 报这个错

 问题解决了吗？ 遇到相同问题了

**Comment by righBai** [comment]
> {“success”：false，“health”：false，“message”：“无法读取null的属性（读取'serverDonation_address'）”}报这个错误

同问，解决了吗？
